"""Create users table

Revision ID: 4c7c660a1eab
Revises: c791a1b9047b
Create Date: 2019-09-26 15:36:25.627304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c660a1eab'
down_revision = 'c791a1b9047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('email', sa.String(length=280), nullable=True),
    sa.Column('api_key', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
