"""Update user table for github oauth

Revision ID: c70816b44dbb
Revises: 4c7c660a1eab
Create Date: 2019-09-27 15:12:42.080508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70816b44dbb'
down_revision = '4c7c660a1eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=280), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('login', sa.String(length=280), nullable=False))
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    op.drop_column('users', 'login')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
